var productFixtures = {
    "1014259": {
        "buy_now_url": "http://74.116.248.195/index.php/checkout/cart/add/uenc/aHR0cDovLzc0LjExNi4yNDguMTk1OjgwODAvYXBpL3Jlc3QvcHJvZHVjdHM_bGltaXQ9Mw,,/product/1014259/",
        "description": "CONTACT MOBILE TEAM FOR ACTIVATION ",
        "entity_id": "1014259",
        "final_price_with_tax": 0.01,
        "image_url": "http://74.116.248.195/media/catalog/product/cache/0/image/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/image.jpg",
        "is_in_stock": true,
        "name": "AT&T ACTIVATION W/ SUBSIDY MUST",
        "product_id": null,
        "product_lastupdated": null,
        "short_description": "AT&T ACTIVATION W/ SUBSIDY MUST",
        "sku": "ATTSUB",
        "type_id": "virtual",
        "url": "http://74.116.248.195/index.php/catalog/product/view/id/1014259/s/at-t-activation-w-subsidy-must/"
    },
    "1014263": {
        "brand_name": "Microsoft",
        "buy_now_url": "http://74.116.248.195/index.php/checkout/cart/add/uenc/aHR0cDovLzc0LjExNi4yNDguMTk1OjgwODAvYXBpL3Jlc3QvcHJvZHVjdHM_bGltaXQ9Mw,,/product/1014263/",
        "description": "Microsoft Office Standard Edition - License and Software Assurance - 1 PC - Annual Fee, Additional Product, Volume - Price Level D - PC",
        "entity_id": "1014263",
        "final_price_with_tax": 113.04,
        "image_url": "https://content.etilize.com/images/300/300/1013085804.jpg",
        "is_in_stock": true,
        "language_supported": "All Languages",
        "license_price_levels": "D",
        "license_pricing": "<ul><li>Annual Fee</li><li>Additional Product</li><li>Volume</li></ul>",
        "license_quantity": "1 PC",
        "license_type": "License & Software Assurance",
        "licensing_program": "Microsoft Open Value Subscription",
        "manufacturer": "Microsoft Corporation",
        "manufacturer_part_number": "021-09108",
        "manufacturer_website_address": "http://www.microsoft.com",
        "name": "Microsoft Office Standard Edition - License and Software Assurance - 1 PC",
        "platform_supported": "PC",
        "product_id": "1013085804",
        "product_lastupdated": null,
        "product_name": "Office Standard Edition",
        "product_type": "Software Licensing",
        "service_&_support": "New Releases Update - Full term",
        "short_description": "Annual Fee, Additional Product, Volume - Price Level D - PC",
        "sku": "BA0011",
        "software_name": "Office Standard Edition",
        "type_id": "virtual",
        "url": "http://74.116.248.195/index.php/catalog/product/view/id/1014263/s/microsoft-office-standard-edition-license-and-software-assurance-1-pc/"
    },
    "1014267": {
        "brand_name": "Microsoft",
        "buy_now_url": "http://74.116.248.195/index.php/checkout/cart/add/uenc/aHR0cDovLzc0LjExNi4yNDguMTk1OjgwODAvYXBpL3Jlc3QvcHJvZHVjdHM_bGltaXQ9Mw,,/product/1014267/",
        "description": "Microsoft Office Standard Edition - License and Software Assurance - 1 PC - Additional Product, Annual Fee - Price Level C - PC - All Languages",
        "entity_id": "1014267",
        "final_price_with_tax": 138.96,
        "image_url": "https://content.etilize.com/images/300/300/1013085805.jpg",
        "is_in_stock": true,
        "language_supported": "All Languages",
        "license_price_levels": "C",
        "license_pricing": "<ul><li>Additional Product</li><li>Annual Fee</li></ul>",
        "license_quantity": "1 PC",
        "license_type": "License & Software Assurance",
        "licensing_program": "Microsoft Open Value Subscription",
        "manufacturer": "Microsoft Corporation",
        "manufacturer_part_number": "021-09202",
        "manufacturer_website_address": "http://www.microsoft.com",
        "name": "Microsoft Office Standard Edition - License and Software Assurance - 1 PC",
        "platform_supported": "PC",
        "product_id": "1013085805",
        "product_lastupdated": null,
        "product_name": "Office  Standard Edition",
        "product_type": "Software Licensing",
        "short_description": "Additional Product, Annual Fee - Price Level C - PC - All Languages",
        "sku": "BA0013",
        "software_name": "Office Standard Edition",
        "type_id": "virtual",
        "url": "http://74.116.248.195/index.php/catalog/product/view/id/1014267/s/microsoft-office-standard-edition-license-and-software-assurance-1-pc/"
    }
}
